[package]
name = "http_testv2"
version = "0.1.0"
authors = ["phw"]

[dependencies]
reqwest = "0.8.6"
json = "0.11.3"
rand = "0.3"
rust-crypto = "0.2.36"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0.70"